"""add equity_curve, drawdown, trades, share_token to backtest_runs

Revision ID: 0aee448384cf
Revises: 7c8be7110c42
Create Date: 2026-08-06 04:15:18.859654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aee448384cf'
down_revision: Union[str, None] = '7c8be7110c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equity_curve', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('drawdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('trades', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('share_token', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_backtest_runs_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_share_token'))
        batch_op.drop_column('share_token')
        batch_op.drop_column('trades')
        batch_op.drop_column('drawdown')
        batch_op.drop_column('equity_curve')

    # ### end Alembic commands ###
